### ISSUE TITLE
*** stack smashing detected ***: node terminated

### ISSUE THREAD

**Issue by fenngineering** [adaltas/node-krb5#12] opened 2018-07-26 15:29 UTC
I'm receiving:

`"*** stack smashing detected ***: node terminated"`

When executing the sync sample code, only modification is changing the yargs object for a config object instead.

I am getting this:-

```
Default principal: user-name@ABC.DEFG.COM

Valid starting     Expires            Service principal
26/07/18 11:04:06  26/07/18 21:04:06  krbtgt/ABC.DEFG.COM@ABC.DEFG.COM
        renew until 02/08/18 11:04:06
26/07/18 11:04:06  26/07/18 21:04:06  HTTP/server01.abc.defg.com@ABC.DEFG.COM
        renew until 02/08/18 11:04:06
26/07/18 11:23:08  26/07/18 21:23:08  krbtgt/ABC.DEFG.COM@ABC.DEFG.COM
        renew until 02/08/18 11:23:08

------------------ spnegoSync:

*** stack smashing detected ***: node terminated
Aborted

```
This is the sample code:-

```
var util = require('util');
var krb5 = require('krb5');
var exec = require('child_process').exec;

var config = {
    principal: 'user-name@ABC.DEFG.COM',
    password: 'AGoodPassword',
    fqdn: 'abc.defg.com'
}

var k = krb5({
  principal: config.principal,
  password: config.password,
  service_fqdn: config.fqdn
});

var do_klist = function(callback){
  process.stderr.write('----------------------- klist:\n\n');
  exec('klist', function(err, stdout, stderr){
    if(err){
      return process.stderr.write('ERROR: ' + err.message + '\n');
    }
    process.stderr.write(stdout + '\n');
    if(typeof(callback)=='function') return callback();
  });
};

var do_kinit = function(){
  process.stderr.write('------------------- kinitSync:\n\n');
  k.kinitSync();
};

var do_kdestroy = function(){
  process.stderr.write('---------------- kdestroySync:\n\n');
  k.kdestroySync();
};

var do_spnego = function(){
  if(config.fqdn){
    process.stderr.write('------------------ spnegoSync:\n\n');
    token = k.tokenSync();
    process.stderr.write('TOKEN: ' + token + '\n\n');
  }
  do_kdestroy();
};

do_kinit();
do_klist(do_spnego);

```

Any suggestions

**Comment by wdavidw** [comment] 2018-08-01 22:11
We have a complete rewrite of the library to make it work with the latest Node.js version. @RReivax  could you share with us when you expect a release ?

**Comment by fenngineering** [comment] 2018-08-02 14:48
This would be a great help to me if you could share this with us.

Kind regards!

**Comment by RReivax** [comment] 2018-08-03 10:41
Current work is on the `napi` branch. It is still a work in progress. Memory errors should not occur again before SPNEGO token generation. 

I am currently fixing an issue regarding SPNEGO authentification and will look into this issue shortly. I'll keep you updated.

**Comment by RReivax** [comment] 2018-10-04 12:27
Sorry for the delay. Rewrite has been published with a new API. These issues should be fixed by now.

**Closed** 2018-11-27 13:37 UTC

**Comment by Rouzz** [comment] 2018-12-20 16:04
Hi,

I'm having the same issue while trying to implement the basic example with a keytab.

```
'use strict'

const krb5 = require('krb5')
const path = require('path')

krb5.kinit({
  principal: 'user@DOMAIN',
  keytab: path.join(__dirname, '../../../resources/user.keytab'),
  realm: 'DOMAIN'
}, function (err, ccname) {
  if (err) {
    console.log(err)
  } else {
    console.log('Credentials saved in', ccname)
    krb5.spnego({
      service_principal: 'user@DOMAIN'
    }, function (err, token) {
      if (err) {
        console.log(err)
      } else {
        console.log('SPNEGO token :', token)
      }
    })
  }
})
```

Here are the logs:
```
Credentials saved in /tmp/krb5cc_1000
*** stack smashing detected ***: node terminated
Aborted (core dumped)
```

I'm not sure what is going on there. If I try to connect using command line it works fine so I'm guessing it's not a problem from the keytab (also the kinit seems to work fine). Here is the logs from command line:
```
Using default cache: /tmp/krb5cc_1000
Using principal: user@DOMAIN
Using keytab: resources/user.keytab
Authenticated to Kerberos v5
```

Any input on what can be going on ?

Node -v: `v8.11.4`

Thank you

**Comment by wdavidw** [comment] 2018-12-20 17:52
Could you try with version 10 of Node.js ?

**Comment by RReivax** [comment] 2018-12-26 16:11
N-API (library used for native bindings) support in Node.js v8.11.4 is an experimental feature. While I'm still unable to reproduce on different environments, consider using at least Node.js v8.12.0, where N-API becomes stable. 

@Rouzz Can you tell me your OS/distribution so that I can have a look? Also which KDC are you using (MIT Kerberos?) ? Would be appreciated.
Thank you for the feedback.
